import { useEffect, useState } from 'react';
import { Inbox, Activity, BadgeDollarSign, CheckCircle2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useRouter } from '@/lib/router';
import { Badge } from '@/components/ui/Badge';
import { STATUS_LABELS, STATUS_STYLES, DEADLINE_LABELS, DEADLINE_STYLES } from '@/lib/constants';
import { formatDateBR } from '@/lib/helpers';
import type { RequestStatus } from '@/lib/types';
export function GestaoPanelScreen(){const {navigate}=useRouter();const [rows,setRows]=useState<any[]>([]);useEffect(()=>{(async()=>{const {data}=await supabase.from('travel_app_requests').select('id,request_number,status,deadline_status,worksite:travel_app_worksites(name),segment:travel_app_segments(origin,destination,departure_date),accommodation:travel_app_accommodations(city,check_in),travelers:travel_app_request_travelers(traveler:travel_app_travelers(full_name))').order('submitted_at',{ascending:true}).limit(50);setRows(data??[])})()},[]);const count=(s:string)=>rows.filter(r=>r.status===s).length;return <div className="space-y-5"><div><h1 className="text-xl font-semibold">Gestão de Viagens</h1><p className="text-sm text-gray-500">Pedidos organizados para atendimento</p></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[[Inbox,'Recebidos',count('pedido_recebido')],[Activity,'Em andamento',count('em_andamento')],[BadgeDollarSign,'Orçados',count('orcado')],[CheckCircle2,'Finalizados',count('finalizada')]].map(([I,l,v]:any)=><div className="rounded-2xl border bg-white p-4"><I className="h-5 w-5 text-[#004883]"/><p className="text-2xl font-semibold mt-2">{v}</p><p className="text-xs text-gray-500">{l}</p></div>)}</div><div className="flex justify-between"><h2 className="font-semibold">Fila de atendimento</h2><button className="text-sm text-[#004883]" onClick={()=>navigate('queue')}>Ver todas</button></div><div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[780px] text-sm"><thead className="bg-gray-50 text-gray-500 text-left"><tr><th className="p-3">Protocolo</th><th className="p-3">Viajante</th><th className="p-3">Trecho</th><th className="p-3">Data</th><th className="p-3">Prazo</th><th className="p-3">Status</th><th></th></tr></thead><tbody>{rows.slice(0,12).map(r=>{const s=r.segment?.[0];const a=r.accommodation?.[0];return <tr className="border-t" key={r.id}><td className="p-3 font-medium">{r.request_number}</td><td className="p-3">{r.travelers?.map((x:any)=>x.traveler?.full_name).filter(Boolean).join(', ')||'—'}</td><td className="p-3">{s?`${s.origin} → ${s.destination}`:a?`Hospedagem em ${a.city||'—'}`:'—'}</td><td className="p-3">{formatDateBR(s?.departure_date||a?.check_in)}</td><td className="p-3"><Badge className={DEADLINE_STYLES[r.deadline_status]}>{DEADLINE_LABELS[r.deadline_status]}</Badge></td><td className="p-3"><Badge className={STATUS_STYLES[r.status as RequestStatus]}>{STATUS_LABELS[r.status as RequestStatus]}</Badge></td><td className="p-3"><button className="text-[#004883] font-medium" onClick={()=>navigate(`request/${r.id}`)}>Abrir</button></td></tr>})}</tbody></table></div></div>}
