import { useEffect, useState } from 'react';
import { PlusCircle, Clock3, CheckCircle2, CalendarClock } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { useRouter } from '@/lib/router';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { STATUS_LABELS, STATUS_STYLES } from '@/lib/constants';
import { formatDateBR } from '@/lib/helpers';
import type { RequestStatus } from '@/lib/types';

type Row=any;
export function HomeScreen(){const {profile}=useAuth();const {navigate}=useRouter();const [rows,setRows]=useState<Row[]>([]);useEffect(()=>{if(!profile)return;(async()=>{const {data}=await supabase.from('travel_app_requests').select('id,request_number,status,request_type,segment:travel_app_segments(origin,destination,departure_date),travelers:travel_app_request_travelers(traveler:travel_app_travelers(full_name))').eq('requester_id',profile.id).order('created_at',{ascending:false}).limit(20);setRows(data??[])})()},[profile]);const active=rows.filter(r=>['pedido_recebido','em_andamento','orcado','aprovado'].includes(r.status));const final=rows.filter(r=>r.status==='finalizada');return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Olá, {profile?.full_name?.split(' ')[0]} 👋</h1><p className="text-gray-500">Solicite e acompanhe suas viagens em um só lugar.</p><Button className="mt-5" onClick={()=>navigate('new-request')}><PlusCircle className="h-5 w-5"/>Nova solicitação</Button></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[[Clock3,'Em andamento',active.length],[CheckCircle2,'Finalizadas',final.length],[CalendarClock,'Próximas viagens',rows.filter(r=>new Date(r.segment?.[0]?.departure_date)>=new Date()).length],[PlusCircle,'Total de pedidos',rows.length]].map(([I,l,v]:any)=><div className="rounded-2xl bg-white border p-4"><I className="h-5 w-5 text-[#004883]"/><p className="text-2xl font-semibold mt-2">{v}</p><p className="text-xs text-gray-500">{l}</p></div>)}</div><section><div className="flex justify-between mb-2"><h2 className="font-semibold">Meus pedidos</h2><button className="text-sm text-[#004883]" onClick={()=>navigate('my-requests')}>Ver todos</button></div><div className="rounded-2xl border bg-white divide-y">{rows.slice(0,8).map(r=>{const s=r.segment?.[0];const names=r.travelers?.map((x:any)=>x.traveler?.full_name).filter(Boolean).join(', ');return <button key={r.id} onClick={()=>navigate(`request/${r.id}`)} className="w-full p-4 text-left hover:bg-gray-50 flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4"><div className="flex-1"><p className="font-medium">{s?.origin} → {s?.destination}</p><p className="text-sm text-gray-500">{names||'—'} · {formatDateBR(s?.departure_date)} · {r.request_number}</p></div><Badge className={STATUS_STYLES[r.status as RequestStatus]}>{STATUS_LABELS[r.status as RequestStatus]}</Badge></button>})}{rows.length===0&&<p className="p-6 text-center text-gray-500">Nenhuma solicitação ainda.</p>}</div></section></div>}
